mysql:
  host: 120.76.247.12
  port: 3306
  database: douyin
  username: root
  password: byte-dance-go

#redis:

address:
  etcd: 127.0.0.1:2379
  api: 0.0.0.0:8080
  user: 127.0.0.1:8081
  comment: 127.0.0.1:8082
  video: 127.0.0.1:8083
  favorite: 127.0.0.1:8084
  chat: 127.0.0.1:8086
  relation: 127.0.0.1:8085

service:
  user: user
  video: video
  comment: comment
  favorite: favorite
  chat: chat
  relation: relation

redis:
  addr: 120.76.247.12:6379
  password: byte-dance-go

oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  access_key_id: LTAI5t8ByvagYGDZE5X7irjc
  access_key_secret: fIwcdIPMeBNxnBwI3nQyBgZpnYafug
  bucket_name: derrick-douyin
  prefix_path: douyin/

resource:
  tmp_dir: /Users/luozhongtian/go/src/douyin/res/